/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/branding";
import { SpellIcon } from "@/components/spell-icon";
import { getDungeon, getMechanic, mechanics } from "@/lib/content-index";
import { categoryLabels, kindLabels, priorityClass, priorityLabels } from "@/lib/labels";
import { getSpellMetadata } from "@/content/generated/spell-metadata";
export function generateStaticParams() { return mechanics.map((mechanic) => ({ mechanicId: mechanic.id })); }
export async function generateMetadata({ params }: { params: Promise<{ mechanicId: string }> }): Promise<Metadata> { const { mechanicId } = await params; const mechanic = getMechanic(mechanicId); return { title: mechanic ? `${mechanic.name} | M+ Debuff Encyclopedia` : "Mechanic not found" }; }
export default async function MechanicPage({ params }: { params: Promise<{ mechanicId: string }> }) { const { mechanicId } = await params; const mechanic = getMechanic(mechanicId); if (!mechanic) notFound(); const dungeon = getDungeon(mechanic.dungeonId); return <><SiteHeader /><main className="shell page-shell"><div className="breadcrumb"><a href="/">Explorer</a><span>/</span><a href={`/dungeons/${mechanic.dungeonId}`}>{dungeon?.name}</a><span>/</span>{mechanic.name}</div><article className="detail-page"><div className="detail-hero"><SpellIcon spellId={mechanic.spellRefs[0]?.spellId ?? 0} size={68} /><div><div className="eyebrow">{dungeon?.name} · {kindLabels[mechanic.kind]}</div><h1>{mechanic.name}</h1><p className="detail-source">Applied by {mechanic.sources.map((source) => source.name).join(" · ")}</p></div><span className={`priority-badge large ${priorityClass[mechanic.priority]}`}>{priorityLabels[mechanic.priority]}</span></div><div className="tag-row detail-tags"><span className="tag category-tag">{categoryLabels[mechanic.primaryCategory]}</span>{mechanic.secondaryCategories.map((category) => <span className="tag" key={category}>{categoryLabels[category]}</span>)}{mechanic.dispelType && <span className="tag">{mechanic.dispelType}</span>}</div><div className="detail-grid"><div><section className="detail-section"><h2>What happens</h2><p>{mechanic.summary}</p></section><section className="detail-section response-section"><h2>Recommended response</h2><p>{mechanic.recommendedResponse}</p></section>{mechanic.highKeyNotes && <section className="detail-section high-key"><span className="eyebrow">High-key note</span><p>{mechanic.highKeyNotes}</p></section>}</div><aside className="detail-aside"><div className="info-card"><span className="eyebrow">Track this</span><strong>{mechanic.trackProminently ? "Prominently" : "Optional"}</strong><p>{mechanic.trackProminently ? "Keep this visible in your main aura or mechanic bar." : "Useful context, but not usually worth a prominent aura slot."}</p></div><div className="info-card"><span className="eyebrow">Relevant to</span><div className="role-pills large-pills">{mechanic.relevantRoles.map((role) => <span className="role-pill" key={role}>{role.toUpperCase()}</span>)}</div></div><div className="info-card"><span className="eyebrow">Spell references</span>{mechanic.spellRefs.map((ref) => <div className="spell-ref" key={`${ref.spellId}-${ref.purpose}`}><span>{ref.spellId}</span><small>{getSpellMetadata(ref.spellId).name} · {ref.purpose.replace("-", " ")}{ref.trackable ? " · trackable" : ""}</small></div>)}</div></aside></div><div className="detail-footer"><span>Reviewed for {mechanic.review.gameVersion} · {mechanic.review.verifiedAt}</span><div className="reference-links">{mechanic.references.map((reference) => <a key={reference.url} href={reference.url} target="_blank" rel="noreferrer">{reference.label} ↗</a>)}</div></div></article></main></>; }
