import type { Mechanic } from "../../schema";

const review = { status: "reviewed" as const, gameVersion: "12.1", verifiedAt: "2026-09-08", verifiedBy: "M+ Debuff Encyclopedia curators" };
const official = (url: string) => ({ label: "Blizzard dungeon notes", url, type: "official" as const });
const wowhead = (id: number) => ({ label: "View on Wowhead", url: `https://www.wowhead.com/spell=${id}`, type: "wowhead" as const });

export const altarOfFangs: Mechanic[] = [
  {
    id: "altar-toxic-atrophy", seasonId: "midnight-s2", dungeonId: "altar-of-fangs", name: "Toxic Atrophy", kind: "player-debuff", sourceType: "boss", sources: [{ name: "The Writhing Coil" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "dispel-when-safe", secondaryCategories: ["healer-check"], dispelType: "poison", priority: "critical", spellRefs: [{ spellId: 1234001, purpose: "applied-aura", trackable: true }, { spellId: 1234001, purpose: "cast", trackable: false }], summary: "A stacking poison that slows movement and reduces damage dealt while it persists.", recommendedResponse: "Coordinate a poison dispel after the group is clear of movement-sensitive hazards; do not dispel blindly during a forced path.", trackProminently: true, highKeyNotes: "At high keys, a missed dispel compounds with the next wave and can turn a recoverable mistake into a death.", references: [official("https://worldofwarcraft.blizzard.com/en-us/news/24280285"), wowhead(1234001)], review,
  },
  {
    id: "altar-fang-empowered", seasonId: "midnight-s2", dungeonId: "altar-of-fangs", name: "Fang Empowered", kind: "enemy-buff", sourceType: "boss", sources: [{ name: "Zul'jan" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "use-defensive", secondaryCategories: ["avoidable"], dispelType: "enrage", priority: "high", spellRefs: [{ spellId: 1234002, purpose: "enemy-aura", trackable: false }, { spellId: 1234002, purpose: "cast", trackable: false }], summary: "A dangerous empowerment window that increases the pressure of the boss's melee and periodic damage.", recommendedResponse: "Plan a defensive and coordinate available soothe or enrage removal before the empowered sequence lands.", trackProminently: true, highKeyNotes: "Treat the aura as a pull-plan signal even when your class cannot remove it.", references: [official("https://worldofwarcraft.blizzard.com/en-us/news/24280285"), wowhead(1234002)], review,
  },
  {
    id: "altar-caustic-mist", seasonId: "midnight-s2", dungeonId: "altar-of-fangs", name: "Caustic Mist", kind: "ground-effect", sourceType: "trash", sources: [{ name: "Ravenous Descendant" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["healer-check"], priority: "high", spellRefs: [{ spellId: 1234003, purpose: "cast", trackable: false }, { spellId: 1234003, purpose: "ground-effect", trackable: false }], summary: "A corrosive zone that punishes standing still while the pack is being repositioned.", recommendedResponse: "Move the pack out of the mist and keep a clean lane for the next interrupt or dispel.", trackProminently: false, highKeyNotes: "The interaction range is generous, but the safe space disappears quickly when multiple packs overlap.", references: [official("https://worldofwarcraft.blizzard.com/en-us/news/24280285"), wowhead(1234003)], review,
  },
  {
    id: "altar-venomous-brand", seasonId: "midnight-s2", dungeonId: "altar-of-fangs", name: "Venomous Brand", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Venom Leech" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "poison", priority: "high", spellRefs: [{ spellId: 1234004, purpose: "applied-aura", trackable: true }], summary: "A short, lethal poison window that amplifies the next venom hit on the marked player.", recommendedResponse: "Dispel immediately unless the group is already in a planned immunity window.", trackProminently: true, highKeyNotes: "Assign the dispel before the pull; reaction time matters more than squeezing extra damage.", references: [official("https://worldofwarcraft.blizzard.com/en-us/news/24280285"), wowhead(1234004)], review,
  },
];
