import type { Mechanic } from "../../schema";
import { appliedAura, cast, enemyAura, makeMechanic, refs, wowhead, guide } from "./shared";

const guideUrl = "https://www.wowhead.com/guide/midnight/den-of-nalorakk-dungeon-overview-location-rewards";

export const denOfNalorakk: Mechanic[] = [
  makeMechanic({ id: "den-toxic-spores", dungeonId: "den-of-nalorakk", name: "Toxic Spores", kind: "player-debuff", sourceType: "boss", sources: [{ name: "The Hoardmonger" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "poison", priority: "critical", spellRefs: [appliedAura(1234846)], summary: "A poison application that deals escalating damage and can overwhelm the group if it remains active.", recommendedResponse: "Dispel immediately, prioritizing targets who will take the next unavoidable hit.", trackProminently: true, highKeyNotes: "Pre-assign poison dispels so simultaneous applications do not consume every cooldown at once.", avoidable: false, references: refs(1234846, "toxic-spores", guideUrl) }),
  makeMechanic({ id: "den-glacial-torment", dungeonId: "den-of-nalorakk", name: "Glacial Torment", kind: "player-debuff", sourceType: "boss", sources: [{ name: "Sentinel of Winter" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "use-defensive", secondaryCategories: ["healer-check"], priority: "high", spellRefs: [appliedAura(1235548)], summary: "A heavy frost damage effect that requires the affected player to survive several ticks.", recommendedResponse: "Use a personal or external defensive and keep the target in healing range; do not treat it as a dispel unless the current patch explicitly supports one.", trackProminently: true, highKeyNotes: "The safest response is planned mitigation before the application rather than late reactionary healing.", avoidable: false, references: refs(1235548, "glacial-torment", guideUrl) }),
  makeMechanic({ id: "den-resourceful-measures", dungeonId: "den-of-nalorakk", name: "Resourceful Measures", kind: "enemy-buff", sourceType: "trash", sources: [{ name: "Hoardmonger trash" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "use-defensive", secondaryCategories: ["avoidable"], priority: "high", spellRefs: [enemyAura(1235072)], summary: "An enemy empowerment that increases the danger of the next pull if it is allowed to ramp.", recommendedResponse: "Interrupt, purge, or focus the empowered enemy according to your group composition; avoid pulling extra packs while it is active.", trackProminently: true, highKeyNotes: "A tank should call this before the next pack so the group can decide whether to purge or kite.", avoidable: true, references: [wowhead(1235072, "resourceful-measures"), guide(guideUrl)] }),
  makeMechanic({ id: "den-putrid-burst", dungeonId: "den-of-nalorakk", name: "Putrid Burst", kind: "ground-effect", sourceType: "trash", sources: [{ name: "Hoardmonger trash" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["healer-check"], priority: "medium", spellRefs: [cast(1245593)], summary: "A ground danger that limits space during already crowded pulls.", recommendedResponse: "Move out immediately and drag the pack away from the pool when possible.", trackProminently: false, highKeyNotes: "Space management matters more than raw damage on fortified high-key routes.", avoidable: true, references: [wowhead(1245593, "putrid-burst"), guide(guideUrl)] }),
];
