import type { Mechanic } from "../../schema";
import { appliedAura, enemyAura, makeMechanic, refs, guide, wowhead } from "./shared";

const guideUrl = "https://www.method.gg/guides/dungeons/kings-rest";

export const kingsRest: Mechanic[] = [
  makeMechanic({ id: "kings-rest-hex-volley", dungeonId: "kings-rest", name: "Hex Volley", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Spectral Witch Doctor" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "curse", priority: "high", spellRefs: [appliedAura(269972)], summary: "A curse volley that spreads pressure across several players and can chain into lethal damage.", recommendedResponse: "Decurse immediately, prioritizing players who are about to take another mechanic.", trackProminently: true, highKeyNotes: "Spread decurses between available players so one healer does not lose all global cooldowns to the volley.", avoidable: false, references: refs(269972, "hex-volley", guideUrl) }),
  makeMechanic({ id: "kings-rest-hex", dungeonId: "kings-rest", name: "Hex", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Spectral Witch Doctor" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "curse", priority: "high", spellRefs: [appliedAura(270492)], summary: "A single-target curse that removes a player from effective play until it is removed.", recommendedResponse: "Decurse quickly; assign a backup decurser if the primary player is moving or crowd-controlled.", trackProminently: true, highKeyNotes: "A missed Hex often costs more time than a missed interrupt, so keep it prominent on healer frames.", avoidable: false, references: refs(270492, "hex", guideUrl) }),
  makeMechanic({ id: "kings-rest-entomb", dungeonId: "kings-rest", name: "Entomb", kind: "player-debuff", sourceType: "boss", sources: [{ name: "Mchimba the Embalmer" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "use-defensive", secondaryCategories: ["healer-check"], priority: "high", spellRefs: [appliedAura(270493)], summary: "A containment effect that removes a player’s ability to help while the group handles the rest of the encounter.", recommendedResponse: "Use a defensive before the application and free the target as soon as the encounter allows.", trackProminently: true, highKeyNotes: "The healer should track both the target and the release timing to avoid wasting cooldowns into the containment.", avoidable: false, references: [wowhead(270493, "entomb"), guide(guideUrl)] }),
  makeMechanic({ id: "kings-rest-unholy-mending", dungeonId: "kings-rest", name: "Unholy Mending", kind: "enemy-buff", sourceType: "trash", sources: [{ name: "Bwonsamdi's agents" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "ignore-low-priority", secondaryCategories: ["avoidable"], priority: "high", spellRefs: [enemyAura(270494)], summary: "A healing effect on an enemy that can undo group progress if it is allowed to complete.", recommendedResponse: "Interrupt or purge it; swap targets only after the cast is stopped.", trackProminently: true, highKeyNotes: "Track the enemy cast in advanced views, but do not export it as a player aura by default.", avoidable: true, references: [wowhead(270494, "unholy-mending"), guide(guideUrl)] }),
];
