import type { Mechanic } from "../../schema";
import { appliedAura, cast, guide, makeMechanic, refs, wowhead } from "./shared";

const guideUrl = "https://www.wowhead.com/guide/midnight/murder-row-dungeon-overview-location-rewards";

export const murderRow: Mechanic[] = [
  makeMechanic({ id: "murder-row-corroding-spittle", dungeonId: "murder-row", name: "Corroding Spittle", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Massive Felwyrm" }, { name: "Kystia Manaheart" }], relevantRoles: ["tank", "healer"], primaryCategory: "dispel-when-safe", secondaryCategories: ["healer-check"], dispelType: "magic", priority: "high", spellRefs: [appliedAura(1228198)], summary: "A stacking magic damage-over-time effect that taxes healing and can become lethal when left on a target.", recommendedResponse: "Dispel after the current damage event when the group is stable; coordinate multiple applications so dispels are not wasted.", trackProminently: true, highKeyNotes: "On high keys, track stacks and the next dispel window rather than reacting only to the icon.", avoidable: false, references: refs(1228198, "corroding-spittle", guideUrl) }),
  makeMechanic({ id: "murder-row-heartstop-poison", dungeonId: "murder-row", name: "Heartstop Poison", kind: "player-debuff", sourceType: "boss", sources: [{ name: "Zaen Bladesorrow" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "poison", priority: "critical", spellRefs: [appliedAura(474515)], summary: "A poison that reduces maximum health while dealing periodic damage.", recommendedResponse: "Remove immediately with a poison dispel; use an external or personal defensive if a dispel is unavailable.", trackProminently: true, highKeyNotes: "Never allow this to overlap with a major boss hit or healing reduction.", avoidable: false, references: refs(474515, "heartstop-poison", guideUrl) }),
  makeMechanic({ id: "murder-row-curse-of-doom", dungeonId: "murder-row", name: "Curse of Doom", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Corrupted Warlock" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "curse", priority: "high", spellRefs: [appliedAura(1217973)], summary: "A delayed curse that detonates for heavy damage if it is allowed to expire.", recommendedResponse: "Decurse promptly; if no decurse is available, use a defensive and prepare for the explosion.", trackProminently: true, highKeyNotes: "Mark the target clearly during caster-heavy pulls so the curse is not hidden among routine debuffs.", avoidable: false, references: refs(1217973, "curse-of-doom", guideUrl) }),
  makeMechanic({ id: "murder-row-felstorm", dungeonId: "murder-row", name: "Felstorm", kind: "cast", sourceType: "boss", sources: [{ name: "Xanthuux the Annihilator" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["use-defensive", "healer-check"], priority: "high", spellRefs: [cast(1228201)], summary: "A sweeping area attack that punishes players who remain in the arena-wide danger zone.", recommendedResponse: "Move to the safe lane and use a defensive if movement or overlap is unavoidable.", trackProminently: true, highKeyNotes: "Treat the cast as a movement check before spending major healing cooldowns.", avoidable: true, references: [guide(guideUrl), wowhead(1228201, "felstorm")] }),
];
