import type { Mechanic } from "../../schema";
import { appliedAura, cast, makeMechanic, refs, guide, wowhead } from "./shared";

const guideUrl = "https://www.icy-veins.com/wow/temple-of-sethraliss-dungeon-guide";

export const templeOfSethraliss: Mechanic[] = [
  makeMechanic({ id: "temple-serrated-charge", dungeonId: "temple-of-sethraliss", name: "Serrated Charge", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Temple trash" }], relevantRoles: ["tank", "healer"], primaryCategory: "use-defensive", secondaryCategories: ["tank-mechanic"], dispelType: "bleed", priority: "high", spellRefs: [appliedAura(1288001)], summary: "A physical bleed that persists through the next sequence of melee damage.", recommendedResponse: "Use a physical mitigation tool and keep the target topped while the bleed runs.", trackProminently: true, highKeyNotes: "Bleed duration, not just the initial hit, determines whether the tank can survive the next pack.", avoidable: false, references: [wowhead(1288001, "serrated-charge"), guide(guideUrl)] }),
  makeMechanic({ id: "temple-poisoned-cheap-shot", dungeonId: "temple-of-sethraliss", name: "Poisoned Cheap Shot", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Temple trash" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-immediately", secondaryCategories: ["healer-check"], dispelType: "poison", priority: "high", spellRefs: [appliedAura(1288002)], summary: "A poison stun setup that can leave a player unable to respond to the next mechanic.", recommendedResponse: "Dispel immediately when possible; otherwise cover the target with a defensive or external.", trackProminently: true, highKeyNotes: "Keep this visible on compact frames because the crowd-control component is easy to miss in combat text.", avoidable: false, references: [wowhead(1288002, "poisoned-cheap-shot"), guide(guideUrl)] }),
  makeMechanic({ id: "temple-lightning-bite", dungeonId: "temple-of-sethraliss", name: "Lightning Bite", kind: "player-debuff", sourceType: "boss", sources: [{ name: "Merektha" }], relevantRoles: ["tank", "healer"], primaryCategory: "tank-mechanic", secondaryCategories: ["use-defensive", "healer-check"], priority: "high", spellRefs: [appliedAura(1290797)], summary: "A tank-targeted periodic lightning effect that makes the next melee sequence harder to stabilize.", recommendedResponse: "Use a tank defensive on the application and plan healing for the subsequent ticks.", trackProminently: true, highKeyNotes: "Pair this with the boss timeline rather than treating it as a random damage-over-time effect.", avoidable: false, references: refs(1290797, "lightning-bite", guideUrl) }),
  makeMechanic({ id: "temple-tempest-winds", dungeonId: "temple-of-sethraliss", name: "Tempest Winds", kind: "cast", sourceType: "environment", sources: [{ name: "Temple of Sethraliss" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["healer-check"], priority: "high", spellRefs: [cast(1288457)], summary: "A wind pattern that pushes players into other hazards if they do not reposition early.", recommendedResponse: "Move with the wind pattern and preserve a safe lane for the next mechanic.", trackProminently: true, highKeyNotes: "Use a cast or timer bar; the damage aura arrives too late to guide movement.", avoidable: true, references: [wowhead(1288457, "tempest-winds"), guide(guideUrl)] }),
];
