import type { Mechanic } from "../../schema";
import { appliedAura, cast, makeMechanic, guide, wowhead } from "./shared";

const guideUrl = "https://wowcarry.com/blog/wow/dungeons/the-blinding-vale-mythic-plus-guide";

export const blindingVale: Mechanic[] = [
  makeMechanic({ id: "blinding-vale-glistening-bloom", dungeonId: "the-blinding-vale", name: "Glistening Bloom", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Lightblossom Trinity" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-when-safe", secondaryCategories: ["healer-check"], dispelType: "magic", priority: "high", spellRefs: [appliedAura(1265001)], summary: "A magic bloom that adds periodic damage while the group is handling the Vale’s light mechanics.", recommendedResponse: "Dispel when the target is safe and not carrying a movement-sensitive mechanic.", trackProminently: true, highKeyNotes: "Plan dispels around the light pattern so a removed aura does not immediately get reapplied by overlap.", avoidable: false, references: [wowhead(1265001, "glistening-bloom"), guide(guideUrl)] }),
  makeMechanic({ id: "blinding-vale-lightwardens-beam", dungeonId: "the-blinding-vale", name: "Lightwarden's Beam", kind: "cast", sourceType: "boss", sources: [{ name: "Lightwarden Ruia" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["healer-check"], priority: "high", spellRefs: [cast(1265002)], summary: "A directional beam that punishes players who fail to respect the boss-facing pattern.", recommendedResponse: "Move out of the beam and keep the boss oriented away from the group.", trackProminently: true, highKeyNotes: "The tank should preserve a predictable facing so melee can react without losing uptime.", avoidable: true, references: [wowhead(1265002, "lightwardens-beam"), guide(guideUrl)] }),
  makeMechanic({ id: "blinding-vale-blinding-light", dungeonId: "the-blinding-vale", name: "Blinding Light", kind: "ground-effect", sourceType: "environment", sources: [{ name: "The Blinding Vale" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["use-defensive"], priority: "high", spellRefs: [cast(1265003)], summary: "A ground pattern that removes safe space and can force overlapping damage when ignored.", recommendedResponse: "Move early, leave room for the next player, and use a defensive if the pattern cannot be avoided.", trackProminently: true, highKeyNotes: "Track the cast or ground marker, not just the resulting damage aura.", avoidable: true, references: [wowhead(1265003, "blinding-light"), guide(guideUrl)] }),
  makeMechanic({ id: "blinding-vale-flourishing-stride", dungeonId: "the-blinding-vale", name: "Flourishing Stride", kind: "enemy-buff", sourceType: "trash", sources: [{ name: "Ziekket" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "ignore-low-priority", secondaryCategories: [], priority: "low", spellRefs: [cast(1265942)], summary: "A movement-oriented enemy effect that is useful context but not normally an aura-bar priority.", recommendedResponse: "Keep it in advanced views only unless your route uses it as a timing cue.", trackProminently: false, highKeyNotes: "Included as a known non-player aura so exports do not accidentally treat it as a debuff.", avoidable: true, references: [wowhead(1265942, "flourishing-stride"), guide(guideUrl)] }),
];
