import type { Mechanic } from "../../schema";
import { appliedAura, cast, makeMechanic, refs, guide, wowhead } from "./shared";

const guideUrl = "https://www.wowhead.com/guide/midnight/voidscar-arena-dungeon-overview-location-rewards";

export const voidscarArena: Mechanic[] = [
  makeMechanic({ id: "voidscar-melt-armor", dungeonId: "voidscar-arena", name: "Melt Armor", kind: "player-debuff", sourceType: "trash", sources: [{ name: "Sycophantic Tarasek" }], relevantRoles: ["tank", "healer"], primaryCategory: "dispel-immediately", secondaryCategories: ["tank-mechanic"], dispelType: "magic", priority: "critical", spellRefs: [appliedAura(1250043)], summary: "A magic armor reduction that makes the next tank hits substantially more dangerous.", recommendedResponse: "Dispel immediately or rotate an external defensive until the debuff is removed.", trackProminently: true, highKeyNotes: "This is a tank-first aura: the healer should see it before the next melee sequence, not after the health drop.", avoidable: false, references: refs(1250043, "melt-armor", guideUrl) }),
  makeMechanic({ id: "voidscar-mind-numbing-poison", dungeonId: "voidscar-arena", name: "Mind-Numbing Poison", kind: "player-debuff", sourceType: "boss", sources: [{ name: "Atroxus" }], relevantRoles: ["healer", "dps"], primaryCategory: "dispel-when-safe", secondaryCategories: ["healer-check"], dispelType: "poison", priority: "high", spellRefs: [appliedAura(1263971)], summary: "A poison that reduces haste and makes recovery from incoming damage slower.", recommendedResponse: "Dispel when safe, prioritizing healers or players about to handle another mechanic.", trackProminently: true, highKeyNotes: "Avoid spending a dispel during an overlap if the target is already stable; remove it before the next throughput check.", avoidable: false, references: refs(1263971, "mind-numbing-poison", guideUrl) }),
  makeMechanic({ id: "voidscar-corrosive-essence", dungeonId: "voidscar-arena", name: "Corrosive Essence", kind: "player-debuff", sourceType: "boss", sources: [{ name: "Agitated Voidscythe" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "use-defensive", secondaryCategories: ["healer-check"], dispelType: "magic", priority: "high", spellRefs: [appliedAura(1263972)], summary: "A corrosive void effect that amplifies the damage of subsequent arena mechanics.", recommendedResponse: "Use a defensive and coordinate a magic dispel after the immediate hit has resolved.", trackProminently: true, highKeyNotes: "Keep the target visible while the arena is moving; losing the debuff in visual clutter is a common high-key failure.", avoidable: false, references: [wowhead(1263972, "corrosive-essence"), guide(guideUrl)] }),
  makeMechanic({ id: "voidscar-thundering-storm", dungeonId: "voidscar-arena", name: "Thundering Storm", kind: "cast", sourceType: "boss", sources: [{ name: "Charonus" }], relevantRoles: ["tank", "healer", "dps"], primaryCategory: "avoidable", secondaryCategories: ["use-defensive", "healer-check"], priority: "high", spellRefs: [cast(1263973)], summary: "A large arena cast that combines movement with unavoidable group damage.", recommendedResponse: "Move to the safe space and use a group defensive if the pattern leaves limited room.", trackProminently: true, highKeyNotes: "The cast timer is more useful than tracking the damage event after it lands.", avoidable: true, references: [wowhead(1263973, "thundering-storm"), guide(guideUrl)] }),
];
